<!-- VUE : Lecture d'une "board" : http://jforum.locahost/index/read/board/# -->
<?php
if (!empty($this->sub)) {
    echo '<div class="listeSections">';
    echo '<table>';

    foreach ($this->sub as $s) {
        $i = 0; $lastMsg = null;
        foreach ($s['topics'] as $suj) {
            $i = $i + count($suj['messages']);
            $lastMsg = end($suj['messages']);
        }
        echo '<tr>';
        echo '<td><a href="/index/read/board/' . $s['info']['id'] . '">' . $s['info']['name'] . '</a></td>';
        echo '<td>' . $s['info']['desc'] . '</td>';
        echo '<td width="100">' . $i . ' message' . ($i > 1 ? 's' : '') . '</td>';
        echo '<td>' . (isset($lastMsg) ? '<a href="/index/read/topic/' . $lastMsg['topic']['id'] . '#' . $lastMsg['info']['id'] . '"><img src="/img/msg.png" alt="M" /></a> ' . $lastMsg['info']['date'] . (isset($lastMsg['user']) ? ' par ' . '<a href="/user/profile/see/' . $lastMsg['user']['id'] . '">' . $lastMsg['user']['login'] . '</a>' : '') : '') . '</td>';
        //echo '<td>' . $lastMsg['info']['date'] . (isset($lastMsg['user']) ? ' par' . $lastMsg['user']['login'] : '') . '</td>';
        echo '</tr>';
        if (!empty($s['sub'])) {
            echo '<tr><td colspan="2" style="padding-left: 15px;">';
            $i = 0;
            foreach ($s['sub'] as $sub) {
                if ($i++ > 0) echo ' - ';
                echo '<a href="/index/read/board/' . $sub['info']['id'] . '">' . $sub['info']['name'] . '</a>';
            }
            echo '</td></tr>';
        }
    }

    echo '</table>';
    echo '</div>';
}
?>

<div class="listeSujets">
<table>
<?php
foreach ($this->topics as $s) {
    echo '<tr>';
    echo '<td><a href="/index/read/topic/' . $s['info']['id'] . '">' . $s['info']['title'] . '</a></td>';
    echo '<td>' . $s['info']['date'] . '</td>';
    echo '<td>' . count($s['messages']) . ' message' . (count($s['messages']) > 1 ? 's' : '') . '</td>';
    echo '<td>Démarré par ' . (isset($s['user']) ? '<a href="/user/profile/see/' . $s['user']['id'] . '">' . $s['user']['login'] . '</a>' : 'Invité') . '</td>';
    echo '</tr>';
}
?>
</table>
</div>

<div id="action">
    <a href="/index/post/board/<?php echo $this->board['id']; ?>">Poster un nouveau sujet</a>
</div>