<!-- VUE : Edition d'un "user" : http://jforum.locahost/user/profile/edit/# -->
<div align="center" style="padding: 10px;">
    <form action="/user/profile/edit/<?php echo $this->member->id; ?>" method="post" style="text-align: left; width: 400px;">
        <fieldset>
        <legend>Informations générales</legend>
        <label for="login">Pseudo :</label>
        <input type="text" name="login" id="login" value="<?php if (isset($this->member->login)) echo $this->member->login; ?>" size="35" />
        <?php if (isset($this->errors['login'])) echo '<img src="/img/stop.png"  style="cursor: help;" title="'.$this->errors['login'].'" />'; ?>
        <br />

        <label for="email">Adresse e-mail :</label>
        <input type="text" name="email" id="email" value="<?php if (isset($this->member->email)) echo $this->member->email; ?>" size="35" />
        <?php if (isset($this->errors['email'])) echo '<img src="/img/stop.png"  style="cursor: help;" title="'.$this->errors['email'].'" />'; ?>
        </fieldset>
        <br />

        <fieldset>
        <legend>Changer de mot de passe</legend>
        <label for="password1">Mot de passe :</label>
        <input type="password" name="password1" id="password1" value="" size="35" />
        <?php if (isset($this->errors['password1'])) echo '<img src="/img/stop.png"  style="cursor: help;" title="'.$this->errors['password1'].'" />'; ?>
        <br />
        <label for="password2">Confirmation :</label>
        <input type="password" name="password2" id="password2" value="" size="35" />
        <?php if (isset($this->errors['password2'])) echo '<img src="/img/stop.png"  style="cursor: help;" title="'.$this->errors['password2'].'" />'; ?>
        </fieldset>
        <br />

        <label for="password" style="width: 137px;">Mot de passe actuel :</label>
        <input type="password" name="password" id="password" value="" size="35" />
        <?php if (isset($this->errors['password'])) echo '<img src="/img/stop.png"  style="cursor: help;" title="'.$this->errors['password'].'" />'; ?>

        <p align="center"><input type="submit" name="action" value="Envoyer" /></p>
    </form>
</div>